import urllib.request
import unittest

print("BASIC TEST FOR SERVER BEING OPEN")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/')
print(stuff.read())
print("BASIC TEST FOR AVAILABILTY LIST")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list')
print(stuff.read())
print("MORE ADVANCED DATABASE QUERIES")
print("LOCATION")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list/1/germany/false/false/false/false')
print(stuff.read())
print("USERNAME")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list/1/false/different/false/false/false')
print(stuff.read())
print("PRICE - 2 of them")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list/2/false/false/false/false/1.50')
print(stuff.read())
print("START TIME")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list/-1/false/false/00:00:09/00:00:17/false')
print(stuff.read())
print("END TIME")
stuff = urllib.request.urlopen('http://127.0.0.1:8000/availability-list/-1/false/false/00:00:00/00:00:07/false')
print(stuff.read())