# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'MealCreditApp_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealCreditApp_iOS

  target 'MealCreditApp_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealCreditApp_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire', '~> 4.5'

end
